### ISSUE TITLE
Could not locate robokit/config.clj

### ISSUE THREAD

**Issue by jaydeesimon** [robert-spurrier/robokit#1]
Randomly came across your project and decided to try it out. Looks pretty cool. :)

I ran `lein bin` and it started to compile but when then got this error:

```
java.io.FileNotFoundException: Could not locate robokit/config__init.class or robokit/config.clj on classpath., compiling:(train.clj:1:1)
Exception in thread "main" java.io.FileNotFoundException: Could not locate robokit/config__init.class or robokit/config.clj on classpath., compiling:(train.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
```

Looks like `config.clj` is missing?

**Comment by robert-spurrier** [comment]
Oops, sorry bout that. Pushed some scruffy code, need to remove that reference to robokit.config, which no longer exists. Will fix today and update!

**Comment by robert-spurrier** [comment]
I polished up the code to remove the cruft, added some more consistent variable naming, more docstrings, etc. Of course removed all traces of namespace relevant to this issue. I was able to build the executable locally with lein bin. Tested that it was running by generating a few midi files. Thanks for the callout!
